# Generated by Django 5.1.7 on 2025-03-17 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_recipient_alter_note_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='author',
            new_name='sender',
        ),
    ]
